const words = [
    {
        weather: 'եղանակ',
        nice: 'գեղեցիկ',
        beautiful: 'գեղեցիկ',
        heavy: 'ծանր',
        easy: 'հեշտ',
        bag: 'պայուսակ',
        nurse: 'դայակ',
        ill: 'հիվանդ',
        hungry: 'քաղցած',
        thirsty: 'ծարավ',
        chair: 'աթոռ',
        comfortable:'հարմարավետ',
        worm: 'տաք',
        sunny: 'արևոտ',
        late: 'ուշ',
        early: 'շուտ',
        coat: 'վերարկու',
        age: 'տարիք',
        job: 'աշխատանք',
        favourite: 'սիրելի',
        angry: 'բարկացած',
        afraid: 'վախեցած',
        cold: 'ցուրտ',
        hot: 'շոգ',
        cheap: 'էժան',
        write: 'գրել',
        short: 'կարճ',
        form: 'ձև',
        different: 'տարբեր',
        close: 'փակել',
        window: 'պատուհան',
        student: 'ուսանող',
        today: 'այսօր',
        tall: 'բարձրահասակ',
        old: 'ծեր',
        but: 'բայց',
        thanks: 'շնորհակալություն',
        again: 'նուրից',
        table: 'սեղան',
        people: 'մարդիկ',
        player: 'խաղացող',
        bed: 'մահճակալ',
        ['a lot of']: 'շատ',
        ['to work']: 'աշխատել',
        job: 'աշխատանք',
        friend: 'ընկեր',
        tired: 'հոգնած',
        kind: 'բարի',
        apple: 'խնձոր',
        ant: 'մրջյուն',
    },
    {
        axe: 'կացին',
        father: 'հայրիկ',
        doll: 'տիկնիկ',
        dog: 'շուն',
        nail: 'մեխ',
        nut: 'ընկույզ',
        nest: 'բույն',
        big: 'մեծ',
        lamp: 'լամպ',
        lion: 'առյուծ',
        lemon: 'լիմոն',
        light: 'լույս',
        king: 'թագաոր',
        key: 'բանալի',
        hen: 'հավ',
        horse: 'ձի',
        house: 'տուն',
        hat: 'գլխարկ',
        hand: 'ձեռք',
        dark: 'մութ',
        sky: 'երկինք',
        wind: 'քամի',
        bus: 'ավտոբուս',
        floor: 'հատակ',
        foot: 'ոտնաթաթ',
        river: 'գետ',
        city: 'քաղաք',
        hair: 'մազ',
        snow: 'ձյուն',
        rain: 'անձրև',
        betwen: 'միջեւ',
        phone: 'հեռախոս',
        letter: 'նամակ',
        tea: 'թեյ',
        umbrella: 'անձրևանոց',
        cat: 'կատու',
        cake: 'տորթ',
        car: 'մեքենա',
        cup: 'բաժակ',
        cock: 'աքաղաղ',
        tree: 'ծառ',
        tiger: 'վագր',
        sun: 'արև',
        spoon: 'գդալ',
        scarf: 'շարֆ',
        bee: 'մեղու',
        desk: 'գրասեղան',
        sell: 'վաճառել',
        yard: 'բակ',
        happy: 'ուրախ',
    },
    {
        milk: 'կաթ',
        fish: 'ձուկ',
        spring: 'գարուն',
        summer: 'ամառ',
        winter: 'ձմեռ',
        box: 'արկղ',
        pig: 'խոզ',
        fly: 'թռչել',
        family: 'ընտանիք',
        autumn: 'աշուն',
        sad: 'տխուր',
        thin: 'նիհար',
        tooth: 'ատամ',
        morning: 'առավոտ',
        evening: 'երեկո',
        afternoon: 'կեսոր',
        teacher: 'ուսուցիչ',
        actor: 'դերասան',
        enginear: 'ինժիներ',
        too: 'նույնպես',
        fair: 'շիկահեր',
        aye: 'աջք',
        ear: 'ականջ',
        nack: 'վիզ',
        finger: 'մատ',
        long: 'երկար',
        ley: 'ոտք',
        face: 'դեմք',
        haney: 'մեղր',
        nose: 'քիթ',
        cheek: 'այտ',
        mouth: 'բերան',
        shoulder: 'ուս',
        arm: 'բազուկ',
        knee: 'ծունկ',
        man: 'տղամարդ',
        ['to have']: 'ունենալ',
        ['to do']: 'անել',
        ['to get']: 'ստանալ',
        ['to take']: 'վերցնել',
        ['to go']: 'գնալ',
        ['to wash']: 'լվանալ',
        ['to dress']: 'հագնվել',
        ['to see']: 'տեսնել',
        woman: 'կին',
        read: 'կարդալ',
        watch: 'դիտել',
        play: 'խաղալ',
        sleep: 'քնել',
        live: 'ապրել',
    },
    {
        make: 'պատրաստել',
        clean: 'մաքրել',
        ox: 'ցուլ',
        come: 'գալ',
        like: 'հավանել',
        pupil: 'աշակերտ',
        goose: 'սագ',
        mouse: 'մուկ',
        louse: 'ոճիլ',
        sand: 'ավազ',
        sound: 'ձայն',
        run: 'վազել',
        pay: 'վճարել',
        hear: 'լսել',
        moon: 'լուսին',
        night: 'գիշեր',
        animal: 'կենդանի',
        ask: 'հարցնել',
        with: 'հետ',
        cloud: 'ամպ',
        eat: 'ուտել',
        empty: 'դատարկ',
        fine: 'հրաշալի',
        frosty: 'սառը',
        greet: 'բարևել',
        hut: 'խրճիթ',
        join: 'միանալ',
        ['every day']: 'ամեն օր',
        ['get up']: 'արթնանալ',
        ['have breakfast']: 'նախաճաշել',
        then: 'հետո',
        before: 'առաջ',
        ['exercise book']: 'աշխատանքային տետր',
        street: 'փողոց',
        want: 'ցանկանալ',
        speak: 'խոսել',
        ['very well']: 'շատ լավ',
        give: 'տալ',
        lesson: 'դաս',
        meet: 'հանդիպել',
        way: 'ճանապարհ',
        become: 'դառնալ',
        always: 'միշտ',
        wait: 'սպասել',
        almost: 'գրեթե',
        pet: 'տնային կենդանի',
        spend: 'անցկացնել',
        holiday: 'արձակուրդ',
        ticket: 'տոմս',
        find: 'գտնել',
    },
    {
        can: 'կարողանալ',
        need: 'կարիք ունենալ',
        parent: 'ծնող',
        husband: 'ամուսին',
        wife: 'կին',
        son: 'որդի',
        arrive: 'ժամանել',
        help: 'օգնել',
        toy: 'խաղալիք',
        busy: 'զբաղված',
        mistake: 'սխալ',
        interesting: 'հետաքրքիր',
        usually: 'սովորաբար',
        clouthes: 'հագուստ',
        tail: 'պոչ',
        flat: 'բնակարան',
        often: 'հաճախ',
        visit: 'այցելել',
        weekend: 'շաբաթ֊կիրակի',
        change: 'փոխել',
        children: 'երեխաներ',
        seldom: 'հազվադեպ',
        classes: 'դասեր',
        ['in time']: 'ժամանակին',
        sweet: 'քաղցր',
        already: 'արդեն',
        page: 'էջ',
        country: 'երկիր',
        diamond: 'ադամանդ',
        swimmer: 'լողորդ',
        interested: 'հետաքրքրված',
        poor: 'աղքատ',
        color: 'գույն',
        shop: 'խանութ',
        near: 'մոտիկ',
        garden: 'այգի',
        person: 'անձ',
        ['go out']: 'գնալ դուրս',
        boat: 'նավ',
        exspensive: 'թանկարժեք',
        hope: 'հույս',
        train: 'գնացք',
        return: 'վերադառնալ',
        shoping: 'առևտուր',
        sheep: 'ոչխար',
        walk: 'քայլել',
        ['capital city']: 'մայրաքաղաք',
        ['have dinner']: 'ճաշել',
        monday: 'երկուշաբթի',
        tuesday: 'երեքշաբթի',
    },
    {
        wetnestday: 'չորեքշաբթի',
        thursday: 'հինգշաբթի',
        friday: 'ուրբաթ',
        week: 'շաբաթ',
        sunday: 'կիրակի',
        dinner: 'ընթրիք',
        office: 'գրասենյակ',
        schoolboy: 'դպրոցական տղա',
        schoolgirl: 'դպրոցական աղչիկ',
        ['at school']: 'դպրոցում',
        ['at home']: 'տանը',
        now: 'հիմա',
        part: 'մաս',
        open: 'բացել',
        sit: 'նստել',
        map: 'քարտեզ',
        roof: 'տանիք',
        wall: 'պատ',
        door: 'դուռ',
        ceiling: 'առաստաղ',
        floor: 'հատակ',
        wardrobe: 'պահարան',
        bookcase: 'գրապահարան',
        mirror: 'հայելի',
        watch: 'ժամացույց',
        armchair: 'բազկաթոռ',
        sofa: 'բազմոց',
        ['TV-set']: 'հեռուստացույց',
        piano: 'դաշնամուր',
        newspaper: 'թերթ',
        hobby: 'սիրելի զբաղմունք',
        stand: 'կանգնել',
        young: 'երիտասարդ',
        year: 'տարի',
        month: 'ամիս',
        catch: 'բռնել',
        ice: 'սառույց',
        orange: 'նարինջ',
        omelette: 'ձվաձեղ',
        owl: 'բու',
        iron: 'արդուկ',
        ['ice-cream']: 'պաղպաղակ',
        ink: 'թանաք',
        ball: 'գնդակ',
        boy: 'տղա',
        book: 'գիրք',
        black: 'սև',
        blue: 'կապույտ',
        bad: 'վատ',
        body: 'մարմին',
    },
    {
        time: 'ժամանակ',
        grass: 'խոտ',
        girl: 'աղջիկ',
        small: 'փոքր',
        egg: 'ձու',
        elephant: 'փիղ',
        envelope: 'ծրար',
        fox: 'աղվես',
        frog: 'գորտ',
        flower: 'ծաղիկ',
        rat: 'առնետ',
        pool: 'լողավազան',
        yarn: 'կծիկ',
        juy: 'սափոր',
        jeep: 'ջիպ',
        jacket: 'ժակետ',
        water: 'ջուր',
        red: 'կարմիր',
        vase: 'վազ',
        van: 'ֆուռգոն',
        bear: 'արջ',
        right: 'ճիշտ',
        word: 'բառ',
        room: 'սենյակ',
        mummy: 'մամա',
        monkey: 'կապիկ',
        rose: 'վարդ',
        ruler: 'քանոն',
        ring: 'մատանի',
        rabbit: 'նապաստակ',
        pen: 'գրիչ',
        pencil: 'մատիտ',
        picture: 'նկար',
        sister: 'քույրիկ',
        brother: 'եղբայր',
        queen: 'թագուհի',
        quilt: 'վերմակ',
        game: 'խաղ',
        worker: 'աշխատող',
        driver: 'վարորդ',
        doctor: 'բժիշկ',
        houseWife: 'տնային տնտեսուհի',
        unicore: 'միաեղջյուր',
        zoo: 'գազանանոց',
        zebra: 'զեբր',
        zipper: 'ցեփ',
        ['x-mas tree']: 'տոնածառ',
        plane: 'օդանավ',
        same: 'նույն',
    },
    {
        fat: 'չաղ',
        sing: 'երգել',
        dance: 'պարել',
        drink: 'խմել',
        answer: 'պատասխան',
        travel: 'ճանապահորդել',
        send: 'ուղարկել',
        tie: 'փողկա',
        mother: 'մայրիկ',
        blackboard: 'գրատախտակ',
        please: 'խնդրել',
        or: 'կամ',
        put: 'դնել',
        yellow: 'դեղին',
        brown: 'շականակագույն',
        ['come in']: 'ներս գալ',
        ['out of']: 'միջից',
        into: 'դեպի մեջ',
        thick: 'հաստ',
        thin: 'բարակ',
        begin: 'սկսել',
        break: 'կոտրել',
        bring: 'բերել',
        build: 'կառուցել',
        buy: 'գնել',
        cost: 'արժենալ',
        drive: 'վարել',
        forget: 'մոռանալ',
        keep: 'պահել',
        know: 'իմանալ',
        classroom: 'դասասենյակ',
        light: 'լուսաոր',
        piece: 'կտոր',
        chalk: 'կավիճ',
        new: 'նոր',
        question: 'հարց',
        ['look at']: 'նայել մի բանի',
        ['go to']: 'գնալ դեպի',
        whose: 'ում',
        factory: 'գործարան',
        paper: 'թուղթ',
        doughter: 'դուստր',
        copy: 'արտագրել',
        language: 'լեզու',
        sentence: 'նախադասություն',
        during: 'ընթացքում',
        solt: 'աղ',
        ['hurry up']: 'շտապել',
        traffic: 'երթեվեկություն',
        win: 'հաղթել',
    },
    {
        boring: 'ձանձրալի',
        fail: 'ձախողել',
        bread: 'հաց',
        enjoy: 'հաճույք ստանալ',
        accident: 'վթար',
        argue: 'վիճել',
        ['turn on']: 'միացնել',
        ['turn off']: 'անջատել',
        believe: 'հավատալ',
        selfish: 'եսասեր',
        bird: 'թռչուն',
        payment: 'վճարում',
        useless: 'անոգտակար',
        usefal: 'օգտակար',
        ['look for']: 'փնտրել',
        at: 'մոտ',
        ['come to']: 'գալ դեպի',
        ['move to']: 'շարժվել դեպի',
        first: 'առաջին',
        learn: 'սովորել',
        foreign: 'օտար',
        center: 'կենտրոն', 
        grammar: 'քերականություն',
        also: 'նաև',
        class: 'դասարան',
        sometimes: 'երբեմն',
        office: 'օֆիս',
        when: 'երբ',
        ['native language']: 'մայրենի լեզու',
        lastname: 'ազգանուն',
        other: 'ուրիշ',
        ['mother country']: 'հայրնիք',
        ['in the chountry']: 'քաղաքից դուրս',
        thousents: 'հազարաոր',
        hundreds: 'հարյուրաոր',
        personal: 'անձնական',
        personally: 'անձամբ',
        native: 'մայրենի',
        place: 'վայր',
        ['tack place']: 'տեղի ունենալ',
        ['in place of']: 'փոխարեն',
        life: 'կյանք',
        wives: 'կանայք',
        suburb: 'արվարձան',
        ['a work of art']: 'արվեստի գերծ',
    },
    {
        noisy: 'աղմկոտ',
        noise: 'աղմուկ',
        reporter: 'լրագրող',
        report: 'զեկուցել',
        ordinary: 'սովորական',
        famous: 'հայտնի',
        exciting: 'հուզիչ',
        excitement: 'հուզմունք',
        excite: 'հուզել',
        boil: 'եռալ',
        teach: 'սովորեցնել',
        ['i am sorry']: 'ցավում եմ',
        believe: 'հավատալ',
        meat: 'միս',
        horror: 'սարսափ',
        ['to work hard']: 'շատ աշխատել',
        ['to have a bath']: 'լոգանք ընդունել',
        use: 'օգտագործել',
        wear: 'հագնել',
        couse: 'պաճառ դառնալ',
        connect: 'կապել',
        mean: 'նշանակել',
        flow: 'լցվել',
        rise: 'ծագել',
        translate: 'թարգմանել',
        rice: 'բրինձ',
        intrerpreter: 'թարգմանիչ',
        liar: 'սուտասան',
        truth: 'ճշմարտություն',
        tip: 'թեյավճար',
        differ: 'տարբերվել',
        careful: 'ուշադիր',
        earn: 'վաստակել',
        wage: 'աշխատավարձ',
        ['eating habit']: 'ուտելու սովորություն',
        God: 'աստված',
        hour: 'ժամ',
        fit: 'ամրակազմ',
        promise: 'խոստանալ',
        ride: 'ձիավարել',
        turn: 'հերթ',
        paint: 'նկարել',
        seaside: 'ծովափ',
        rest: 'հանգիստ',
        stay: 'մնալ',
    },
    {
        station: 'կայարան',
        guest: 'հյուր',
        leave: 'մեկնել',
        boast: 'պարծենալ',
        lough: 'ծիծաղել',
        repair: 'վերանորոգել',
        about: 'մասին',
        ['come from']: 'առաջանալ, ծագել',
        pollution: 'աղտոտում',
        dirt: 'կեղտ',
        spoil: 'փչացնել',
        harm: 'վնասել',
        health: 'առողջություն',
        dangerous: 'վտանգաոր',
        trip: 'ճամփորդություն',
        leave: 'հեռանալ, մեկնել, լքել, թողնել',
        cook: 'եփել, պատրաստել',
        someon: 'ինչորմեկը',
        lie: 'պառկել',
        married: 'ամուսնացած',
        ['relation ship']: 'հարաբերությունների մեջ',
        single: 'միայնակ',
        differance: 'տարբերություն',
        difficult: 'դժվար',
        generally: 'ընդհանրապես',
        never: 'երփեք',
        ['once a week']: 'շաբաթական 1 անգամ',
        every: 'ամեն',
        large: 'ընարձակ, մեծ',
        imagine: 'պատկերացնել',
        ['who know']: 'ով իմանա?',
        bicycle: 'հեծանիվ',
        course: 'դասընթաց',
        plant: 'բույս',
        ['to plain']: 'տնկել',
        pain: 'ցավ',
        medicine: 'դեղորայք',
        drug: 'դեղ (թմրանյութ)',
        pill: 'դեղ (կոճակ)',
        tablet: 'դեղ (կապսուլա)',
        ['pain killer']: 'ցավազրկող',
        pharmacy: 'դեղատուն',
        temperature: 'ջերմություն',
        cough: 'հազալ',
    },
    {
        sneeze : 'փռշտալ',
        yawn : 'հորանջել',
        cut : 'կտրել',
        bruis: 'կապտուկ',
        graze : 'քերծվածք',
        blood : 'արյուն',
        bleed : 'արյունահոսել',
        bandage : 'վիրակապ',
        plaster : 'սանտավիկ',
        stop : 'դադարեցնել',
        toothache : 'ատամնացավ',
        headack : 'գլխացավ',
        stamacack : 'ստամոքսի ցավ',
        ['to spread'] : 'տարածել',
        body : 'մարմին',
        ['body parts'] : 'մարմնի մասեր',
        head : 'գլուխ',
        hear : 'մազ',
        chin : 'դունչ',
        forehead : 'ճակատ',
        neck : 'վիզ',
        shoulder : 'ուս',
        chest : 'կրծքավանդակ',
        arm : 'բազուկ',
        elbow : 'արմունկ',
        hend : 'ձերք',
        palm : 'ձեռքի ափ',
        finger : 'մատ',
        thumb : 'բութ մատ',
        nail : 'եղունգ, մեխ',
        ['index finger'] : 'ցուցամատ',
        ['middle finger'] : 'միջնեմատ',
        index : 'ցուցիչ',
        back : 'մեջք, հետ',
        heel : 'կռունկ',
        toe : 'ոտքի մատեր',
        prefer : 'նախընտրելի',
        ['ring finger'] : 'մատնեմատ',
        ['little finger'] : 'ճկույտ',
        become : 'դառնալ',
        here : 'այստեղ',
        cheat : 'խաբել',
        raven : 'ագռավ',
    },
    {
        who : 'ով',
        where : 'որտեղ',
        how : 'ինչպես',
        ['how old'] : 'քանի տարեկան',
        ['how many'] : 'քանի (հաշվելիների համար)',
        ['how much'] : 'քանի (անհաշվելիների համար)',
        arrive : 'ժամանել',
        coat : 'վերարկու',
        arrival : 'ժամանում',
        depart : 'մեկնել',
        departure : 'մեկնում',
        ['arrive in'] : 'ժամանել տարածքով մեծ տեղ',
        ['arrive at'] : 'ժամանել տարածքով փոքր տեղ',
        ['hard-working'] : 'աշխատասեր',
        own : 'սեփական',
        solve : 'լուծել',
        ['by myself'] : 'ինքս ինձնով',
        spend : 'անցկացնել',
        ['spend time'] : 'ժամանակ ծախսել',
        ['spend mony'] : 'գումար ծախսել',
        think : 'մտածել',
        ['the same way'] : 'նույն ձևով',
        talanted : 'շնորհալի',
        genious : 'հանճար',
        colorful : 'գունագեղ',
        colorless : 'անգույն',
        polite : 'քաղաքավարի',
        possible : 'հնարաոր',
        ['in the and'] : 'իվերջո',
        ['at the and'] : 'ինչոր բանի վերջում',
        impossible : 'անհնար',
        finnaly: 'վերջապես',
        hammer : 'չակուչ',
        delicious : 'ախորժալի',
        tasty : 'համեղ',
        curious : 'հետաքրքրասեր',
        ['go back'] : 'ետ գնալ',
        boastful : 'պարծենկոտ',
        deaf : 'խուլ',
        noisy : 'աղմկել',
    },
    {
        deafeniny : 'խլացնող',
        exam : 'քննություն',
        severally : 'մի քանի օր',
        so : 'այսպիսով',
        rearly : 'մոտաորապես',
        another : 'մեկ ուրիշ',
        unknown : 'անծանոթ',
        think : 'կարծել',
        ['in my opinion'] : 'իմ կարծիքով',
        funny : 'զվարճալի',
        lose : 'կորցնել',
        modest : 'համեստ',
        pationt : 'համբերատար',
        impationt : 'անհամբեր',
        witty : 'սրամիտ',
        lare : 'ալարկոտ',
        bony : 'ոսկոր',
        bill : 'հաշիվ',
        free : 'անվճար',
        ['each other'] : 'միմիանց',
        ['one another'] : 'մեկմեկու',
        understand : 'հասկանալ',
        enough : 'բավականին',
        lend : 'պարտքով տալ',
        borrow : 'պարտքով վերցնել',
        ugly : 'գեշ',
        emotional : 'եմոցիոնալ',
        ['at the moment'] : 'այս պահին',
        ['right now'] : 'հենց հիմա',
        ['do not make a noise'] : 'մի աղմկեք',
        sleepy : 'քունը տանել',
        agrre : 'համաձայնել',
    },
    {
        appreciate : 'գնահատել',
        ['belonge to'] : 'պատկանել',
        hate : 'ատել',
        love : 'սիրել',
        dislike : 'չհավանել',
        ['seem to'] : 'թվալ',
        remembre : 'հիշել',
        recognire : 'ճանաչել',
        complete : 'ավարտել',
        swim : 'լողանալ',
        quiet : 'հանգիստ, հանդարտ',
        present : 'ներկա',
        absent : 'բացակա',
        happen : 'պատահել',
        shine : 'փայլել',
        immediately: 'անմիջապես',
        smail : 'ժպտալ',
        ['the best'] : 'լավագույն',
        ['the worst'] : 'վատագույն',
        town : 'փոքրիկ քաղաք',
        nead : 'կոկիկ',
        bridge : 'կամուրջ',
        ['to my surprise'] : 'ի զարմանս ինձ',
        ['how are things going'] : 'ինչպես են գործերը գնում',
        illness : 'հիվանդություն',
        flu : 'գրիպ',
        air : 'օդ',
        ['to make a decision'] : 'որոշում կայացնել',
        fall : 'ընկնել',
        repeat : 'կրկնել',
        vocabulary : 'բառապաշար',
        becouse : 'որովհետևվ',
        ['becouse of'] : 'պատճառով',
        ['due to'] : 'շնորհիվ',
        branch : 'ճյուղ',
        eyesight : 'տեսողություն',
        sense : 'իմաստ, նշանակություն',
        say : 'ասել',
        ['in a week'] : 'մեկ շաբաթից',
    },
    {
        ['any more'] : 'այլևս',
        ['to be going to']  : 'պատրաստվել ինչ֊որ բան անել',
        yesterday : 'երեկ',
        ['the day before yesterday'] : 'երեկ չէ առաջին օրը',
        ['last day'] : 'անցյալ օրը',
        ['last week'] : 'անցյալ շաբաթ',
        ['last month'] : 'անցյալ ամիս',
        complain : 'դժգոհել',
        see : 'նայել (ակամայից տեսնել)',
        look : 'նայել (մտադրված նայել)',
        watch : 'նայել (դիտել ինչ որ բան)',
        hear : 'լսել (ակամայից լսել)',
        listen : 'լսել (մտադրված լսել)',
        movie : 'կինո',
        beat : 'ծեծել',
        blow : 'հարված',
        draw : 'ոչ ոքի',
        grow : 'աճել',
        hang : 'կախել',
        hit : 'հարվածել',
        lose : 'կորցնել',
        mean : 'նկատի ունենալ',
        spend : 'ծախսել',
        win : 'հաղթել',
        extraordinary : 'արտասոր',
        fast : 'արագ',
        variable : 'փոփոխական',
        mood : 'տրամադրություն',
        high : 'բարձր',
        low : 'ցածր',
        influence : 'ազդել',
        recently : 'վերջերս',
        neetral : 'չեզոք',
        ['no more']: 'այլևս',
        swimming : 'լողալ',
        notice : 'նկատել',
        praise : 'գովել',
        memorise : 'մտապահել',
        even : 'նույնիսկ',
    },
    {
        objact : 'առարկա',
        carry : 'կրել',
        wallet : 'դրամապանակ',
        ability : 'ունակություն',
        suddenly : 'հանկարծ',
        disappear : 'անհայտանալ',
        mittens : 'ձեռնոց',
        necklace : 'վզնոց',
        earring : 'ականջող',
        socks : 'նասկիներ',
        rubber : 'ռետին',
        knife : 'դանակ',
        sharpen : 'սրել',
        sharpener : 'սրիչ',
        sharpknife : 'սուր դանակ',
        bluntknife : 'քյոռ դանակ',
        fileholder : 'պապկա (թղթապանակ)',
        sanglasses : 'արևային ակնոց',
        coast : 'ափ',
        seed : 'սերմ',
        guns : 'հրացան',
        tame : 'վարժեցնել',
        goats : 'այծ',
        until : 'մինչև որ',
        along : 'երկայնքով',
        anything : 'ինչ որ բան',
        side : 'կողմ',
        island : 'կղզի',
        probably : 'հավանաբար',
        native : 'բնիկ',
        explore : 'հետազոտոել',
        more : 'ավելի',
        against : 'ընդդեմ',
        decided : 'որոշել',
        some : 'մի քանի',
        attract : 'գրավել',
        however : 'այնուամենայնիվ',
        wreak : 'բեկոր',
        wort : 'արշեք',
        ['fall asleep'] : 'քնով ընկնել',
        somebody : 'ինչ որ մեկը',
        nobody : 'ոչ ոք',
        follow : 'հետևել',
        inspector : 'տեսուչ',
        software : 'ծրագրային ապահովում',
        ready : 'պատրաստ',
        sure : 'վստահ',
    },
    {
        foy : 'մառախուղ',
        storm : 'փոթորիկ',
        about : 'մոտաորապես',
        ['one by one'] : 'մեկ առ մեկ',
        into : 'մեջ',
        pillow : 'բարձ',
        towel : 'սրբիչ',
        soap : 'օճառ',
        closet : 'զգեստապահարան',
        shelf : 'դարակ',
        substitute : 'փոխարինող',
        reminder : 'հիշեցում',
        utilites : 'կողմնակի ծառայություններ',
        current : 'ընթացիկ',
        learning : 'ուսուցում',
        interrupt : 'ընդատել',
        ['differ from'] : 'տարբերվել ինչ֊որ բանից',
        magazine : 'ամսագիր',
        lost : 'պարտվել',
        shirts : 'սառոչկա',
        most : 'ամենա',
        positive : 'դրական',
        comparative : 'համեմատական',
        supertaive : 'գերադրական',
        than : 'քան',
        adjective : 'ածական',
        everything : 'ամեն ինչ',
        need : 'անհրաժեշտություն',
        ['becouse of'] : 'պատճառով',
        features : 'հատկություններ',
        suddenly: 'հանկարծակի',
        then : 'ապա',
        concept : 'գաղափար',
        ever : 'երբևէ',
        without : 'առանց',
        custom  : 'սովորույթ',
        which : 'որը',
        inside : 'ներսում',
        replace : 'փոխարինել',
        ['similar to'] : 'նման',
    },
    {
        beginning : 'սկիզբ',
        usage : 'օգտագործումը',
        nothing : 'ոչինչ',
        expect : 'ակնկալել',
        doubt : 'կասկած',
        ['no doubt'] : 'կասկած չկա',
        behind : 'հետևում',
        inner : 'ներքին',
        way : 'ճանապարհ',
        will : 'կամք',
        directive : 'հրահանգ',
        ['no worries'] : 'ոչ մի անհանգստություն',
        means : 'միջոց',
        reuse : 'վերաոգտագործում',
        through : 'միջոցով',
        any : 'ցանկացած',
        ['any where'] : 'ցանկացած տեղ',
        ['any thing'] : 'ցանկացած բան',
        ['any time'] : 'ցանկացած ժամանակ',
        similarity : 'նմանություն',
        beginner : 'սկսնակ',
        ['no where'] : 'ոչ մի տեղ',
        ['no one'] : 'ոչ մեկ',
        ['no how'] : 'ոչ մի ձև',
        undoubtedly : 'անկասկած',
        doubtful : 'կասկածամիտ',
        above : 'վերևում',
        below : 'ներքևում',
        out : 'դուրս',
        inside : 'դրսում',
        ['will-power ']: 'կամքի ոժ',
        weak : 'թույլ',
        invite : 'հրավիրել',
        relative : 'բարեկամ',
        apply : 'դիմել',
        individual : 'անհատական',
        together : 'միասին',
        illustrate : 'պարզաբանել',
        detect: 'հայտնաբերել',
        plain : 'պարզ',
        layer : 'շերտ',
        based : 'հիմնված',
        sustainable : 'կայուն',
        goal : 'նպատակ',
        fulfill : 'կատարել',
        flexible : 'ճկուն',
        kit : 'հավաքածու',
    },
    {
        ['it means'] : 'նշանակում է',
        consider : 'հաշվի առնել',
        ['set up'] : 'կարգաորում',
        each : 'յուրաքանչյուր',
        additional : 'լրացուցիչ',
        however : 'սակայն',
        basic : 'հիմնական',
        predictable : 'կանխատեսելի',
        inspired : 'ոքեշնչված',
        enable : 'ակտիվացնել',
        decouples : 'անջատում',
        ['make it'] : 'անել դա',
        divided : 'բաժանված',
        rule : 'կանոն',
        ['very posible'] : 'շատ հնարաոր է',
        chapter : 'գլխում',
        besides : 'բացի այդ',
        responsible : 'պատասխանատու',
        logical : 'տրամաբանական',
        effort : 'ջանքեր',
        state : 'վիճակ',
        appearance : 'արտաքին տեսք',
        character : 'բնաորություն',
        match : 'մրցում',
        ['to gain'] : 'ձեռք բերել',
        still : 'դեռևս',
        injured : 'վնասված',
        cure : 'բուժում',
        ['for mounts'] : 'ամիսներով',
        except : 'բացի (բացառելով)',
        ads : 'գովազդ',
        achieve : 'նվաճել',
        degree : 'աստիճան',
        turn : 'շրջվել',
        still : 'դեռ',
        injured : 'վնասվածք',
        fealing : 'զգացմունք',
        nationality : 'ազգություն',
        description : 'նկարագրություն',
        besides : 'բացի (ներառելով)',
    },
    {
        ['one of these days'] : 'օրերից մի օր',
        bright : 'պայծառ',
        bride : 'հարս',
        groom : 'փեսա',
        participate : 'մասնակցել',
        serious : 'լուրջ',
        kidding : 'ձեռ առնել',
        remove : 'հեռացնել',
        routine : 'ռեժիմ',
        untill : 'մինչև (պայմանով)',
        till : 'մինչև (առանց պայման)',
        habit : 'սովորություն',
        explanation : 'բացառություն',
        ['in the way'] : 'ճանապարհին',
        ['by the way'] : 'իմիջալիոց',
        ['thats all'] : 'այդքանը',
        that : 'այն, որ',
        acompany : 'ուղեկցել',
        extain : 'գործողություն',
        goin : 'ձեռք բերել',
        luck : 'բախտ',
        lucky : 'բախտաոր',
        maybe : 'երևի',
        outer : 'արտաքին',
        cross : 'խաչ',
        crossroad : 'խաչմերուկ',
        sidewelk : 'մայթ',
        common : 'հասարակ',
        proper : 'հատուկ',
        countable : 'հաշվելի',
        uncountable : 'անհաշվելի',
        advice : 'խորհուրդ',
        singuler : 'եզակի',
        plural : 'հոգնակի',
        what : 'ինչ',
        who : 'ով',
        where : 'որտեղ',
        when : 'երբ',
        why : 'ինչու',
        how : 'ինչպես',
        from : 'որտեղից',
        whose : 'ում',
    },
    {
        where : 'որտեղ',
        on : 'վրա',
        in : 'մեջ',
        under : 'տակ',
        to : 'դեպի',
        ['out of'] : 'միջից',
        into : 'դեպի մեջ',
        ['come in'] : 'ներս գալ',
        ['go out'] : 'դուրս գալ',
        for : 'համար',
        or : 'կամ',
        and : 'և',
        one : 1,
        two : 2,
        three : 3,
        four : 4,
        five : 5,
        six : 6,
        seven : 7,
        eight : 8,
        nine : 9,
        ten : 10,
        eleven : 11,
        twelve : 12,
        thirteen : 13,
        fourteen : 14,
        fifteen : 15,
        sixteen : 16,
        seventeen : 17,
        eighteen : 18,
        nineteen : 19,
        twenty : 20,
        thirty : 30,
        forty : 40,
        fifty : 50,
        sixty : 60,
        seventy : 70,
        eighty : 80,
        ninety : 90,
        hundred : 100,
        thousend : 1000,
        lie : 'ստել',
        rise : 'բարձրանալ',
        tell : 'պատմել',
        bite : 'կծել',
        drow : 'երազել',
        fight : 'պայքարել',
        hide : 'թաքցնել',
        hurt : 'վիրաորել',
        keep : 'պահպանել',
    },
    {
        bend : 'թեքել',
        ['to tell the thruth'] : 'ճիշտն ասած',
        solution : 'լուծում',
        ['all the day'] : 'ամբողջ օրը',
        ['the whole day'] : 'ամբողջ օրը',
        ['nothing special'] : 'առանձնապես ոչ մի բան',
        reason : 'պատճառ',
        cause : 'հետևանք',
        ['what kind of'] : 'ինչ տեսակի',
        ['what type of'] : 'ինչ տիպի',
        like : 'հավանել',
        skip : 'բաց թողնել',
        ['at somepoint'] : 'ինչ֊որ պահի',
        society : 'հասարակություն',
        contrary : 'հակառակը',
        right : 'ճիշտ',
        wrong : 'սխալ',
        simply : 'պարզապես',
        actually : 'իրականում',
        especially : 'հատկապես',
        ['i share your opinion'] : 'ես կիսում եմ ձեր կարծիքը',
        ['set off'] : 'ճանապարհ ընկնել',
        ['see off'] : 'ճանապարհել',
        ['sliping beg'] : 'քնապարկ',
        bathroom : 'բաղնիք',
        bath : 'լոգանք',
        some : 'որոշ',
        slow : 'դանդաղ',
        disaster : 'աղետ',
        disasterous : 'աղետալի',
        collect : 'հավաքել',
        ['no mether'] : 'կարևոր չի',
        chaind : 'շղթա',
        forgiv : 'ներել',
        moreover : 'դեռ ավելին',
        ['in the beginning'] : 'սկզբում',
    },
    {
        ['in the and'] : 'վերջում',
        impression : 'տպաորություն',
        impressive : 'տպաորիչ',
        impressed : 'տպաորված',
        behave : 'վարվել',
        behaviour : 'վարվելաձև',
        ['behave yourself'] : 'հավաքի քեզ',
        astrologer : 'աստղագետ',
        nature : 'բնույթ',
        explaretion : 'բացատրություն',
        ['some of them'] : 'նրանցից ոմանք',
        ['until this time'] : 'մինչև այս պահը',
        undiscovered : 'չբացահայտված',
        drawings : 'գծագրեր',
        device : 'սարք',
        contains : 'պարունակում է',
        continuation : 'շարունակություն',
        landscape : 'բնապատկեր',
        according : 'համաձայն',
        transparent : 'թափանցիկ',
        coincides : 'համընկնում է',
        ['introvert man'] : 'փակ մարդ',
        ['extrovert man'] : 'շփող մարդ',
        communicative : 'շփող',
        includ : 'ներառել',
        proof : 'ապացույց',
        annoing : 'նեռվայնացնող',
        ['deal with'] : 'առնչվել խնդիրների հետ',
        pot : 'թավա',
        patient : 'համբերություն',
        plate : 'ափսե',
        fork : 'պատարաքաղ',
        soft : 'փափուկ',
        fregile : 'փխրուն',
        unique : 'եզակի',
        expose : 'ընկղմել',
        encourage : 'խրախուսել',
    },
    {
        aproach : 'մոտեցում',
        exaduraion : 'չափազանցված',
        solobrading : 'տոնել, նշել',
        passion : 'կիրք',
        passionate : 'կրքոտ',
        stair : 'փիլաքյան',
        resigniton : 'հրաժարական',
        interviewer :  'հարցավար',
        intervie : 'հարցազրույց',
        interviever : 'հարցազրույց տվող',
        employer : 'գործատու',
        employee : 'աշխատող',
        trainee : 'սովորող',
        trainer : 'սովորեցնող',
        bright : 'պայծառ',
        round : 'կլոր',
        profit : 'շահույթ',
        profitble : 'շահութաբեր',
        might : 'հզոր',
        that : 'որ',
        war : 'պատերազմ',
        against : 'դեմ',
        fair : 'արդար',
        wise : 'իմաստուն',
        peace : 'խաղաղություն',
        desir : 'ցանկություն',
        lay : 'պառկել',
        accept : 'ընդունել',
        offer : 'առաջարկ',
        suppose : 'ենթադրել',
        dishonored : 'անպատիժ',
        deport : 'արտաքսում',
        ride : 'զբոսանք',
        castle : 'ամրոց',
        lord : 'տեր',
        lordship : 'տիրապետություն',
        messenger : 'սուրհանդակ',
        message : 'հաղորդագրություն',
        hardly : 'հազիվ, զոռով',
        exist : 'գոյություն ունենալ',
        thing : 'բան',
        temporary : 'ժամանակաոր',
        permanent : 'մշտական',
    },
    {
        over : 'վրայով',
        choice : 'ընտրություն',
        brackets : 'փակագծեր',
        arrange : 'կազմակերպել',
        arrangement : 'կազմակերպվածություն',
        arranged : 'կազմակերպված',
        last : 'վերջինը',
        plane : 'ինքնաթիռ',
        nervous : 'նիարդային',
        flight : 'թռիչք',
        stranger : 'օտար',
        tissue : 'անձեռոցիկ',
        scary : 'վախենալու',
        cellar : 'նկուղ',
        quotes : 'չակերտ',
        space : 'տարածություն, բացատ',
        ['figure brackets'] : 'ձևաոր փակագիծ',
        oversleep : 'քնած մնալ',
        overthink : 'շատ մտածված',
        overcooked : 'շատ եփված',
        undercooked : 'քիչ եփված',
        underthink : 'քիչ մտածված',
        overrated : 'գերագնահատված',
        underrated : 'թերագնահատված',
        rated : 'գնահատել',
        join : 'միանալ',
        order : 'պատվիրել',
        too : 'չափազանց',
        pleased : 'գոհ',
        pleaseing : 'գոհացնող',
        pleasure : 'հաճույք',
        enter : 'մուտք',
        ['to prove']: 'ապացուցել',
        sometimes: 'երբեմն',
        ['due to']: 'շնորհիվ',
        ['i do not mind']: 'դեմ չեմ',
        attentive: 'ուշադիր',
        ['what the matter']: 'ինչ է պատահել',
        quick: 'արագ',
        ['shout at']: 'գոռալ',
        talk: 'խոսել',
        
    },
];

const container = document.createElement('div');
container.classList.add('container');

const putWordInContainer = (_word) => {
    const word = document.createElement('p');
    container.classList.add('word');
    word.innerHTML = _word;   
    container.appendChild(word);
};

const wordSections = words[Math.floor(Math.random() * words.length)];
const failWords = [];

for(let key in wordSections) {
    const answer = prompt(wordSections[key]);
    if(answer !== key) {
        failWords.push(`${wordSections[key]} --- ${key}`)
    }
}

failWords.forEach((el) => {
    putWordInContainer(el);
});

document.body.appendChild(container);